"use client"
import { Inter } from 'next/font/google';
import Navbar from '../components/Navbar';
import './globals.css';

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}



import ToasterContext from '../components/TosterContext';
import NextAuthProvider from './provider.js';

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} container mx-auto`}>
        <NextAuthProvider>
          <ToasterContext />
          <Navbar />
          {children}
        </NextAuthProvider>
      </body>
    </html>
  )
}
